twig:
  file_name_pattern: "*.twig"

  #   # Configuration pour l'environnement de test
  #   when@test:
  #     strict_variables: true

  # Thèmes de formulaire
  form_themes:
    - "bootstrap_5_layout.html.twig"
